config/routes.rb
Gerkart::Application.routes.draw do

  root :to => 'home#index'
  resources :championships do
    resources :drivers, :controller => 'championship_drivers'
    resources :rounds, :controller => 'rounds'
    resources :ranking_configurations, :controller => 'ranking_configurations'
  end
  resources :drivers
  resources :tracks

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :drivers
  has_many :rounds

  def build_ranking
    conf = RankingConfiguration.build_for(self)
    conf.default = 0
    ranking = Hash.new

    drivers.each do |driver|
        driverRank = {:points => 0, :rounds => []}
        rounds.each do |round|
            roundPosition = round.roundPositions.find(lambda { RoundPosition.new }) {|item| item[:round_id] == round.id and item[:driver_id] == driver.id}
            driverRank[:rounds] << {:position => roundPosition.position, :points => conf[roundPosition.position]}
            driverRank[:points] = driverRank[:points] + conf[roundPosition.position]
        end

        find_worst_round(driverRank) do |worst_round|
            worst_round[:drop] = true
            driverRank[:points] = driverRank[:points] - worst_round[:points]
        end

        ranking[driver] = driverRank
    end

    Hash[ranking.sort_by {|driver, results| -results[:points]}]
  end

  def find_worst_round driverRank
    if driverRank[:rounds].length > 0
        yield(driverRank[:rounds].min_by{|round| round[:points].nil?? 0 : round[:points] })
    end
  end
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  attr_accessible :email, :name
  has_and_belongs_to_many :championships
end

app/models/ranking_configuration.rb
class RankingConfiguration < ActiveRecord::Base
  belongs_to :championship
  attr_accessible :points, :position

  def self.build_for championship
    Hash[where(:championship_id => championship.id).all.map{|item| [item.position, item.points]}]
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :date, :name
  belongs_to :championship
  belongs_to :track
  has_many :roundPositions, :order => 'round_positions.position'
  has_many :drivers, :through => :roundPositions
  accepts_nested_attributes_for :roundPositions

  def winner
    roundPositions.select {|v| v.position == 1 }.first
  end
end

app/models/round_position.rb
class RoundPosition < ActiveRecord::Base
  belongs_to :round
  belongs_to :driver
  attr_accessible :position, :total_time
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/championship_drivers_controller.rb
class ChampionshipDriversController < ApplicationController
    def index
        @championship = Championship.includes(:drivers).find(params[:championship_id])
        @available_drivers = Driver.all - @championship.drivers
    end

    def create
        @championship = Championship.find(params[:championship_id])
        @championship.drivers <<  Driver.find(params[:driver_id])
        redirect_to :action => 'index', :championship_id => params[:championship_id]
    end
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
    def new
        @championship = Championship.new
    end

    def index
        @championships = Championship.all
    end

    def show
        @championship = Championship.includes(:rounds => :roundPositions).find(params[:id])

        @ranking = @championship.build_ranking
    end

    def create
        @championship = Championship.create(params[:championship])

        redirect_to :action => :show, :id => @championship.id
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
    def new
        @driver = Driver.new
    end

    def index
        @drivers = Driver.all
    end

    def create
        @driver = Driver.create(params[:driver])

        redirect_to :action => :show, :id => @driver.id
    end

    def show
        @driver = Driver.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/ranking_configurations_controller.rb
class RankingConfigurationsController < ApplicationController
    def create
        @rankingConfiguration = RankingConfiguration.new(params[:ranking_configuration])
        @rankingConfiguration.championship_id = params[:championship_id]
        @rankingConfiguration.save

        redirect_to :action => 'index'
    end

    def index
        @rankingConfiguration = RankingConfiguration.new
        @championship = Championship.find(params[:championship_id])

        @rankingConfigurations = RankingConfiguration.where(:championship_id => params[:championship_id]).order(:position)
    end

    def destroy
        RankingConfiguration.find(params[:id]).destroy
        redirect_to :action => 'index'
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
    def new
        @championship = Championship.includes(:drivers).find(params[:championship_id])
        @round = Round.new
        @round.track = Track.new
        @available_tracks = Track.all
        @roundPositions = initialize_roundPositions @championship.drivers
    end

    def initialize_roundPositions drivers
        roundPositions = Array.new
        drivers.each do |driver|
            roundPosition = RoundPosition.new
            roundPosition.driver = driver
            roundPositions << roundPosition
        end
        return roundPositions
    end

    def edit
        @round = Round.includes(:championship, :track, :drivers).find(params[:id])
        @championship = @round.championship
        @roundPositions = @round.roundPositions + initialize_roundPositions(@championship.drivers - @round.drivers)
        @available_tracks = Track.all
    end

    def update
        round = Round.find(params[:id])
        round.name = params[:round][:name]
        round.date = params[:round][:date]
        round.track = Track.find(params[:round][:track])
        Round.transaction do
            RoundPosition.delete_all(:round_id => params[:id])
            create_round_positions round, params
            round.save
        end
        redirect_to :action => :show, :championship_id => params[:championship_id], :id => round.id
    end

    def create
        round = Round.new(params[:round].slice(:name, :date))
        round.championship = Championship.find(params[:championship_id])
        round.track = Track.find(params[:round][:track])
        create_round_positions round, params
        round.save

        redirect_to :action => :show, :championship_id => params[:championship_id], :id => round.id
    end

    def create_round_positions round, params
        params[:round][:roundPositions_attributes].each do |standing|
            if !standing[1][:position].empty?
                roundPosition = round.roundPositions.build(standing[1].slice(:position, :total_time))
                roundPosition.driver = Driver.find(standing[1][:driver_id])
            end
        end
    end

    def show
        @championship = Championship.find(params[:championship_id])
        @round = Round.where(:id => params[:id], :championship_id => params[:championship_id]).first
    end

    def index
        @championship = Championship.find(params[:championship_id])

        @rounds = Round.includes(:track, :roundPositions => [:driver]).where(:championship_id => params[:championship_id], :round_positions => {:position => 1 })
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def index
        @tracks = Track.all
    end

    def new
        @track = Track.new
    end

    def create
        Track.new(params[:track]).save

        redirect_to :action => :index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/championship_drivers/index.html.erb
<h2><%= link_to @championship.name, @championship %> > Drivers </h2>

<ul>
<% @championship.drivers.each do |driver| %>
    <li><%= driver.name %></li>
<% end %>
</li>

<% if !@available_drivers.empty? %>
    <p>Add drivers to championship:</p>
    <%= form_tag do %>
        <%= select_tag(:driver_id, options_from_collection_for_select(@available_drivers, :id, :name), :multiple => true) %>
        <%= submit_tag %>
    <% end %>
<% end %>

app/views/championships/index.html.erb
<h2>Championships</h2>

<p><%= link_to 'Create Championship', new_championship_path %></p>

<ul>
<% @championships.each do |championship| %>
    <li><%= link_to championship.name, championship %></li>
<% end %>
</ul>

app/views/championships/new.html.erb
<h2><%= link_to 'Championships', :championships %> > Create Championship</h2>

<%= form_for (@championship) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <div class='actions'>
        <%= f.submit %>
    </div>
<% end %>

app/views/championships/show.html.erb
<h2>Championship: <%= @championship.name %></h2>
<p>
<%= link_to 'Drivers', [@championship, :drivers] %>
<%= link_to 'Rounds', [@championship, :rounds] %>
<%= link_to 'Ranking Configuration', [@championship, :ranking_configurations] %>
</p>
<h3>Ranking:</h3>

<table>
    <thead>
        <tr>
            <th>Position</th>
            <th>Driver</th>
            <% @championship.rounds.each do |round| %>
            <th><%= round.name %>
            <% end %>
            <th>Points</th>
        <tr>
    </thead>
    <tbody>
    <% @ranking.each_with_index do |(driver, results), index| %>
        <tr>
            <td><%= index + 1 %>
            <td><%= driver.name %></td>
            <% results[:rounds].each do |round| %>
                <td class="<%= round[:drop]? 'drop' : '' %>"><%= round[:points] %><%= round[:position].nil?? '' : ' (' + round[:position].to_s + 'º)' %> </td>
            <% end %>
            <td><%= results[:points] %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/drivers/index.html.erb
<h2>Drivers</h2>

<p><%= link_to 'Create Driver', new_driver_path %></p>

<ul>
<% @drivers.each do |driver| %>
    <li><%= driver.name %></li>
<% end %>
</ul>

app/views/drivers/new.html.erb
<h2><%= link_to 'Drivers', :drivers %> > Create Driver</h2>

<%= form_for(@driver) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <div class="action">
        <%= f.submit %>
    </div>
<% end %>

app/views/drivers/show.html.erb
<h2>Drivers > <%= @driver.name %> </h2>

app/views/home/index.html.erb
<h2>Gerkart</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gerkart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <header>
            <nav class="round">
                <ul class="menu">
                    <li><%= link_to 'Championships', :championships %></li>
                    <li><%= link_to 'Drivers', :drivers %></li>
                    <li><%= link_to 'Tracks', :tracks %></li>
                </ul>
            </nav>
        </header>
        <section class="round">
            <%= yield %>
        </section>
    </div>
</body>
</html>

app/views/ranking_configurations/index.html.erb
<h2><%= link_to @championship.name, @championship %> > Ranking Configuration</h2>

<table>
    <thead>
        <tr>
            <th>&nbsp</th>
            <th>Position</th>
            <th>Points</th>
        </tr>
    </thead>
    <tbody>
<% @rankingConfigurations.each do |rankingConfiguration| %>
        <tr>
            <td><%= button_to 'delete', [@championship, rankingConfiguration], :method => 'delete'  %></td>
            <td><%= rankingConfiguration.position %>
            <td><%= rankingConfiguration.points %>
        </tr>
<% end %>
    </tbody>
</table>

<%= form_for ([@championship, @rankingConfiguration]) do |f| %>
    <%= f.label :position %>
    <%= f.text_field :position %>

    <%= f.label :points %>
    <%= f.text_field :points %>
    <%= f.submit %>
<% end %>

app/views/rounds/_round.html.erb
<%= form_for [@championship, @round] do |f| %>
<p>
    <%= f.label :date %>
    <%= f.text_field :date, :size => 10, :value => f.object.date.nil?? '' : f.object.date.strftime("%d/%m/%Y") %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :track %>
    <%= f.select :track, options_from_collection_for_select(@available_tracks, :id, :name, @round.track.id) %>
</p>
<table>
    <thead>
        <tr>
            <th>Driver</th>
            <th>Position</th>
            <th>Total Time</th>
        </tr>
    </thead>
    <tbody>
        <%= f.fields_for :roundPositions, @roundPositions, :include_id => false do |driver_fields| %>
            <tr>
               <td><%= driver_fields.hidden_field :driver_id %><%= driver_fields.object.driver.name %></td>
               <td><%= driver_fields.text_field :position, :size => 3 %></td>
               <td><%= driver_fields.text_field :total_time, :size => 10, :value => driver_fields.object.total_time && driver_fields.object.total_time.strftime("%H:%M:%S") %></td>
            </tr>
        <% end %>
    </tbody>
</table>

    <%= f.submit %>
<% end %>

app/views/rounds/edit.html.erb
<h2><%= link_to @championship.name, @championship %> > <%= link_to 'Rounds', [@championship, :rounds] %> > Edit Round</h2>

<%= render 'round' %>

app/views/rounds/index.html.erb
<h2><%= link_to @championship.name, @championship %> > Rounds</h2>

<p><%= link_to 'Create Round', new_championship_round_path%></p>

<table>
    <thead>
        <tr>
            <th>Round Name</th>
            <th>Track</th>
            <th>Date</th>
            <th>Winner</th>
            <th>Total Time</th>
        </tr>
    </thead>
    <tbody>
<% @rounds.each do |round| %>
    <tr>
        <td><%= link_to round.name, championship_round_path(:id => round.id) %></a></td>
        <td><%=round.track.name%></td>
        <td><%=round.date.strftime '%d/%m/%Y' %></td>
        <td><%=round.winner.driver.name %></td>
        <td><%=round.winner.total_time.strftime '%T' unless round.winner.total_time.nil? %></td>
<% end %>
    </tbody>
</table

app/views/rounds/new.html.erb
<h2><%= link_to @championship.name, @championship %> > <%= link_to 'Rounds', [@championship, :rounds] %> > Create Rounds</h2>

<%= render 'round' %>

app/views/rounds/show.html.erb
<h2><%= link_to @championship.name, @championship %> > Rounds</h2>

<h3><%= @round.date.strftime("%d/%m/%Y") %> - <%= @round.name %> - <%= @round.track.name %></h3>

<table>
    <thead>
        <tr>
            <th>Position</th>
            <th>Driver</th>
            <th>Total Time</th>
        </tr>
    </thead>
    <tbody>
<% @round.roundPositions.includes(:driver).each do |r| %>
        <tr>
            <td><%= r.position %></td>
            <td><%= r.driver.name %></td>
            <td><%= r.total_time.strftime("%H:%M:%S") unless r.total_time.nil? %></td>
        </tr>
<% end %>
    </tbody>
</table>

<%= link_to 'Edit Round', edit_championship_round_path %>

app/views/tracks/index.html.erb
<h2>Tracks</h2>

<p><%= link_to 'Create Track', new_track_path%></p>

<% if !@tracks.nil? %>
    <ul>
    <% @tracks.each do |t| %>
        <li><%= t.name %></li>
    <% end %>
    </ul>
<% end %>

app/views/tracks/new.html.erb
<h2><%= link_to 'Tracks', :tracks %> > Create Track</h2>

<%= form_for(@track) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>